export const skillOptions = [
    { label: 'Pediatrician', value: 'Pediatrician' },
    { label: 'General Practitioner', value: 'General_Practitioner' },
    { label: 'Surgeon', value: 'Surgeon' },
    { label: 'Paramedic', value: 'Paramedic' },
    { label: 'Emergency Physician', value: 'Emergency_Physician' },
    { label: 'Nurse', value: 'Nurse' },
    { label: 'Anesthesiologist', value: 'Anesthesiologist' },
    { label: 'Cardiologist', value: 'Cardiologist' },
    { label: 'Respiratory Therapist', value: 'Respiratory_Therapist' },
    { label: 'Orthopedic Specialist', value: 'Orthopedic_Specialist' },
    { label: 'Neurologist', value: 'Neurologist' },
    { label: 'Oncologist', value: 'Oncologist' },
    { label: 'Obstetrician', value: 'Obstetrician' },
    { label: 'Trauma Surgeon', value: 'Trauma_Surgeon' },
    { label: 'Psychiatrist', value: 'Psychiatrist' },
    { label: 'Infectious Disease Specialist', value: 'Infectious_Disease_Specialist' },
    { label: 'Radiologist', value: 'Radiologist' },
    { label: 'Pharmacist', value: 'Pharmacist' },
    { label: 'Dentist', value: 'Dentist' },
    { label: 'Physical Therapist', value: 'Physical_Therapist' },
    { label: 'Dermatologist', value: 'Dermatologist' },
    { label: 'Endocrinologist', value: 'Endocrinologist' },
    { label: 'Gastroenterologist', value: 'Gastroenterologist' },
    { label: 'Nephrologist', value: 'Nephrologist' },
    { label: 'Ophthalmologist', value: 'Ophthalmologist' },
    { label: 'Optometrist', value: 'Optometrist' },
    { label: 'Pulmonologist', value: 'Pulmonologist' },
    { label: 'Radiation Oncologist', value: 'Radiation_Oncologist' },
    { label: 'Allergist/Immunologist', value: 'Allergist_Immunologist' },
    { label: 'Rheumatologist', value: 'Rheumatologist' },
    { label: 'Urologist', value: 'Urologist' },
    { label: 'Audiologist', value: 'Audiologist' },
    { label: 'Clinical Pathologist', value: 'Clinical_Pathologist' },
    { label: 'Forensic Pathologist', value: 'Forensic_Pathologist' },
    { label: 'Geneticist', value: 'Geneticist' },
    { label: 'Hematologist', value: 'Hematologist' },
    { label: 'Invasive Cardiologist', value: 'Invasive_Cardiologist' },
    { label: 'Interventional Radiologist', value: 'Interventional_Radiologist' },
    { label: 'Nuclear Medicine Specialist', value: 'Nuclear_Medicine_Specialist' },
    { label: 'Pain Management Specialist', value: 'Pain_Management_Specialist' },
    { label: 'Palliative Care Specialist', value: 'Palliative_Care_Specialist' },
    { label: 'Perinatologist', value: 'Perinatologist' },
    { label: 'Plastic Surgeon', value: 'Plastic_Surgeon' },
    { label: 'Psychologist', value: 'Psychologist' },
    { label: 'Reproductive Endocrinologist', value: 'Reproductive_Endocrinologist' },
    { label: 'Speech-Language Pathologist', value: 'Speech_Language_Pathologist' },
    { label: 'Sports Medicine Specialist', value: 'Sports_Medicine_Specialist' },
    { label: 'Toxicologist', value: 'Toxicologist' },
    { label: 'Vascular Surgeon', value: 'Vascular_Surgeon' },
    { label: 'Virologist', value: 'Virologist' },
    { label: 'Wound Care Specialist', value: 'Wound_Care_Specialist' },
    { label: 'Occupational Therapist', value: 'Occupational_Therapist' },
    { label: 'Clinical Psychologist', value: 'Clinical_Psychologist' },
    { label: 'Podiatrist', value: 'Podiatrist' },
    { label: 'Geriatric Specialist', value: 'Geriatric_Specialist' },
    { label: 'Dietitian', value: 'Dietitian' }
  ]